level1 = {'terrain': '../Levels/1/Level1_tiles.csv',
          'terrain_skin': '../Graphics/Textures/Level1_tiles/Level1Floor+Collectibles.png',
          'indoor': '../Levels/1/Level1_indoor.csv',
          'indoor_skin': '../Graphics/Textures/Level1_tiles/Lvl1BackgroundTiles.png',
          'player': '../Levels/1/Level1_player.csv',
          'player_skin': '../Graphics/Character/fiveselof.png',
          'collectible': '../Levels/1/Level1_collectible.csv',
          'obstacle': '../Levels/1/Level1_obstacle.csv',
          'obstacle_skin': '../Graphics/Textures/WetFloorSign.png',
          'enemy': '../Levels/1/Level1_enemy.csv',
          'enemy_skin': '../Graphics/Character/elof.png',
          'music': '../Sounds/Magic Scout - Farm.mp3',
          'constraint': '../Levels/1/Level1_constraint.csv',
          'flag': '../Levels/1/Level1_flag.csv',
          'background': '../Graphics/Textures/Backgrounds/bg.png',
          'node_pos': (200, 200),
          'unlock': 1}

level2 = {'terrain': '../Levels/2/Level2_tiles.csv',
          'terrain_skin': '../Graphics/Textures/Level2_tiles/Lvl2Floor.png',
          'indoor': '../Levels/2/Level2_indoor.csv',
          'indoor_skin': '../Graphics/Textures/Level2_tiles/Lvl2Background.png',
          'player': '../Levels/2/Level2_player.csv',
          'player_skin': '../Graphics/Character/ptelof.png',
          'collectible': '../Levels/2/Level2_collectible.csv',
          'obstacle': '../Levels/2/Level2_obstacle.csv',
          'obstacle_skin': '../Graphics/Textures/Cones.png',
          'enemy': '../Levels/2/Level2_enemy.csv',
          'enemy_skin': '../Graphics/Character/elof.png',
          'music': '../Sounds/Getting it Done.mp3',
          'constraint': '../Levels/2/Level2_constraint.csv',
          'flag': '../Levels/2/Level2_flag.csv',
          'background': '../Graphics/Textures/Backgrounds/Level2_bg.png',
          'node_pos': (400, 600),
          'unlock': 2}

level3 = {'terrain': '../Levels/3/Level3_tiles.csv',
          'terrain_skin': '../Graphics/Textures/tile.png',
          'indoor': '../Levels/3/Level3_indoor.csv',
          'indoor_skin': '../Graphics/Textures/Level1_tiles/Lvl1TilesV1.png',
          'player': '../Levels/3/Level3_player.csv',
          'player_skin': '../Graphics/Character/elof.png',
          'collectible': '../Levels/3/Level3_collectible.csv',
          'obstacle': '../Levels/3/Level3_obstacle.csv',
          'obstacle_skin': '../Graphics/Textures/WetFloorSign.png',
          'enemy': '../Levels/3/Level3_enemy.csv',
          'enemy_skin': '../Graphics/Character/MP.png',
          'music': '../Sounds/TheForest.wav',
          'constraint': '../Levels/3/Level3_constraint.csv',
          'flag': '../Levels/3/Level3_flag.csv',
          'background': '../Graphics/Textures/Backgrounds/Level3_bg.png',
          'node_pos': (600, 250),
          'unlock': 3}

level4 = {'terrain': '../Levels/4/Level4_tiles.csv',
          'terrain_skin': '../Graphics/Textures/tile.png',
          'indoor': '../Levels/4/Level4_indoor.csv',
          'indoor_skin': '../Graphics/Textures/Level1_tiles/Lvl1TilesV1.png',
          'player': '../Levels/4/Level4_player.csv',
          'player_skin': '../Graphics/Character/scarletselof.png',
          'collectible': '../Levels/4/Level4_collectible.csv',
          'obstacle': '../Levels/4/Level4_obstacle.csv',
          'obstacle_skin': '../Graphics/Textures/WetFloorSign.png',
          'enemy': '../Levels/4/Level4_enemy.csv',
          'enemy_skin': '../Graphics/Character/MP.png',
          'music': '../Sounds/French.mp3',
          'constraint': '../Levels/4/Level4_constraint.csv',
          'flag': '../Levels/4/Level4_flag.csv',
          'background': '../Graphics/Textures/Backgrounds/bg.png',
          'node_pos': (850, 550),
          'unlock': 4}


levels = {
    0: level1,
    1: level2,
    2: level3,
    3: level4}
